### PR TITLE
Error if entropy is missing

### PR DESCRIPTION
**Pull request by c1728p9**
Explicitly error if entropy is missing rather than letting compilation fail on the linking step.

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
I don't like this approach.
You are fixing this application, but this issue still remains.

I feel like this should be in mbedTLS, because they are publishing those functions in public headers but not providing stubs when they are compiled out.

**Comment by c1728p9** [comment]
I created PR https://github.com/ARMmbed/mbed-os/pull/3069 as an alternative fix. I also opened an issue in mbed-os to give an entropy missing error if the headers are used - https://github.com/ARMmbed/mbed-os/issues/3071.

**Comment by c1728p9** [comment]
I updated this PR so it only applies to Thread. That way the Nanostack library won't cause linker issues when coap functions are missing.

**Comment by c1728p9** [comment]
Done here instead - https://github.com/ARMmbed/mbed-os/pull/3069

**Pull request closed without merging**
